(define (problem rubik_test)
    (:domain rubik)
    (:objects r w b g o y - color)
    (:init
        (color1 r g y)
        (color2 w b r)
        (color3 y b y)
        (color4 r w g)
        (color5 w o b)
        (color6 y b r)
        (color7 g w y)
        (color8 g y y)
    )
    (:goal (and
        (color1 o g w)
        (color2 o b w)
        (color3 r g w)
        (color4 r b w)
        (color5 o g y)
        (color6 o b y)
        (color7 r g y)
        (color8 r b y)
        )
    )
)