(define (problem rubik_test_fp)
    (:domain rubik)
    (:objects r w b g o y - color)
    (:init
        (color1 o w b)
        (color2 o y b)
        (color3 r g w)
        (color4 r b w)
        (color5 o w g)
        (color6 o y g)
        (color7 r g y)
        (color8 r b y)
    )
    (:goal (and
        (color1 o g w)
        (color2 o b w)
        (color3 r g w)
        (color4 r b w)
        (color5 o g y)
        (color6 o b y)
        (color7 r g y)
        (color8 r b y)
        )
    )
)