# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyinterpreter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyinterpreter.proto',
  package='pyinterpreter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13pyinterpreter.proto\x12\rpyinterpreter\"\x1a\n\x0b\x45valRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x18\n\tEvalReply\x12\x0b\n\x03msg\x18\x01 \x01(\t2L\n\nEvaluation\x12>\n\x04\x65val\x12\x1a.pyinterpreter.EvalRequest\x1a\x18.pyinterpreter.EvalReply\"\x00\x62\x06proto3')
)




_EVALREQUEST = _descriptor.Descriptor(
  name='EvalRequest',
  full_name='pyinterpreter.EvalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pyinterpreter.EvalRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_EVALREPLY = _descriptor.Descriptor(
  name='EvalReply',
  full_name='pyinterpreter.EvalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pyinterpreter.EvalReply.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['EvalRequest'] = _EVALREQUEST
DESCRIPTOR.message_types_by_name['EvalReply'] = _EVALREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EvalRequest = _reflection.GeneratedProtocolMessageType('EvalRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALREQUEST,
  '__module__' : 'pyinterpreter_pb2'
  # @@protoc_insertion_point(class_scope:pyinterpreter.EvalRequest)
  })
_sym_db.RegisterMessage(EvalRequest)

EvalReply = _reflection.GeneratedProtocolMessageType('EvalReply', (_message.Message,), {
  'DESCRIPTOR' : _EVALREPLY,
  '__module__' : 'pyinterpreter_pb2'
  # @@protoc_insertion_point(class_scope:pyinterpreter.EvalReply)
  })
_sym_db.RegisterMessage(EvalReply)



_EVALUATION = _descriptor.ServiceDescriptor(
  name='Evaluation',
  full_name='pyinterpreter.Evaluation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=92,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='eval',
    full_name='pyinterpreter.Evaluation.eval',
    index=0,
    containing_service=None,
    input_type=_EVALREQUEST,
    output_type=_EVALREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVALUATION)

DESCRIPTOR.services_by_name['Evaluation'] = _EVALUATION

# @@protoc_insertion_point(module_scope)
